### ISSUE TITLE
hyphen normalization

### ISSUE THREAD

**Issue by gorinars** [aditya-joglekar/FS02_Scoring_Toolkit#2]
Hello,

Just wanted to confirm.
Currently, we have some words with hyphen ("-") in reference annotations.
Such tokens are currently fully removed by the normalization.

I see 3 options, but not sure which one is the best:
- replace hyphen with space
- remove hyphens
- keep words with hyphen

Not sure which one is the best, but I believe some of these would be useful to unify the input from the participants

**Comment by gorinars** [comment]
For me sounds like replacing hyphen with space (adding to https://github.com/AJoGaTech/FS02_Scoring_Toolkit/blob/ca4ebb7b9da50a199230f47e5c6702d979e9fe30/scutils/fs02utils.py#L167) is probably the most reasonable option

**Comment by aditya-joglekar** [comment]
Thank you for suggesting those changes! Made those changes, closing this issue now.
